### ISSUE TITLE
Logging compatibility with Python Server

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-syncstorage#136]
As we inch towards a production ready server it's important to not break downstream metrics that is dependent on the raw server logs.

The current sync statistics work is tracked in [bug 1291340](https://bugzilla.mozilla.org/show_bug.cgi?id=1291340) and @dannycoates has written [parsing code](https://github.com/dannycoates/smt) for the raw protobuf heka logs.

Diving into the ([metrics requirements](https://bugzilla.mozilla.org
/show_bug.cgi?id=1291340#c4)) and the transform.js source code it appears that go syncstorage only needs to publish some specific fields: 
- `method` - http request method
- `path` - http request path
- `code` - http response code
- `request_time` - float, in seconds 
- `fxa_uid` - from tokenserver's token
- `device_id`  - from tokenserver's token
- `agent` - the user agent string from the user 

The rest of the data will be [derived](https://github.com/dannycoates/smt/blob/master/defaults/transform.js) or created by heka (user_agent_*). 

So the scope of work appears to be: 
- generate a non-standard [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) line with the required fields above
- configure heka to parse user agent and ship the logs to the main aggregator and S3

@whd and @dannycoates does the above sound accurate?

**Comment by whd** [comment]
If "generate a non-standard mozlog line" means emitting a log line with the fields as described above, this sounds right to me. I'm guessing non-standard is referring to specifically how the mozlog go library works by default.

The standard heka and mozlog decoder/configuration will decode the `agent` field into the other agent vars with no additional configuration.

**Comment by mostlygeek** [comment]
@whd I sent @dannycoates two PRs to support both sync's format and mozlog format. Now the `fxa_uid` and `device_id` just need to be added to the logging handler and it _should_ output all the necessary information.
