### ISSUE TITLE
Test harness needed

### ISSUE THREAD

**Issue by joeblew99** [mozilla-services/go-syncstorage#158]
The code has tests.
But it would be useful if a test client be done.

Benefits:
Writing tests to find conflict race conditions.
Writing http tests
 Network benchmarking.

**Comment by joeblew99** [comment]
Also the same storage backing can be used on the test clients. In this case sql-lite.

This makes it easy because the same code as the server can be used for the clients.

Also shared error message can be easily used and so the integration tests can actively use these. I can imagine this will be useful for writing complex tests

**Comment by joeblew99** [comment]
A perfect example of what we want on the client is.

412 Precondition Failed response:

r = server.get("/collection")
last_modified = r.headers["X-Last-Modified"]

bsos = generate_changes_to_the_collection()

headers = {"X-If-Unmodified-Since": last_modified}
r = server.post("/collection", bsos, headers)
if r.status == 412:
    print "WRITE FAILED DUE TO CONCURRENT EDITS"

The client may choose to abort the write, or to merge the changes from the server and re-try with an updated value of X-Last-Modified.

**Comment by mostlygeek** [comment]
The python server is the original implementation for the spec. I prioritized passing the python server's functional tests over having them in go. This is done in the [circle.yml configuration](https://github.com/mozilla-services/go-syncstorage/blob/master/circle.yml#L77-L81). There's a lot of edge casesl and the python server's functional tests are mostly complete for documenting those.

**Comment by mostlygeek** [comment]
This [chunk of code](https://github.com/mozilla-services/go-syncstorage/blob/master/web/syncUserHandler.go#L265-L299) prevents parallel HTTP access per user. So there's only one writer or reader for a user's DB at any time. 

The server will 412 when an X-If-Unmodified-Since condition fails.

**Comment by joeblew99** [comment]
@mostlygeek ok thansk for the feedback.
