### ISSUE TITLE
PPR proposal

### ISSUE THREAD

**Issue by joeblew99** [mozilla-services/go-syncstorage#160]
Wondering if you will accept PR's for:

Add a 2nd dB option like Ql. Ql is 100℅ golang and relational like sql-lite.
It also works with Gorm, but ngorm has no reflection and runs on servers, desktops and mobiles.

https://github.com/ngorm/ql

**Comment by mostlygeek** [comment]
I certainly do appreciate PRs. However, I would suggest forking the repo to support different a different database. sqlite was chosen since it is well known, supported and stable.
