### ISSUE TITLE
GET storage/<uid>/collection should default to unlimited

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-syncstorage#166]
The server currently has a default GET BSO of 1000 objects. If a limit is not specified by the client should it default to unlimited? 

Even though there is no limit the server will send back an X-Weave-Next-Offset header.

@rfk What is the correct behavior in this case? Send back everything or internally limit the query with the X-Weave-Next-Offset?

**Comment by rfk** [comment]
Yes, the python server defaults to "no limit".  Perhaps we should add an explicit test case for this?  (Although I guess there's always an X such that a default limit of > X would let the test pass).

Can you confirm from server logs whether clients were making any non-limited calls, and hence might have failed to receive some items?

**Comment by mostlygeek** [comment]
The server has received unlimited calls :( 
I shall fix this.

**Comment by rfk** [comment]
> The server has received unlimited calls

Out of curiosity, from what clients?  If they're up-to-date ones, we should see about making those clients to pagination.

**Comment by mostlygeek** [comment]
Took a sample. Appears to be mostly desktop firefox. Since there's a 1000 BSO limit, I just filtered for the biggest collections. 

````
$ grep -E 'GET.*storage.*(bookmarks|history|forms)' access.log | grep -v limit | grep -v 'ids=' | awk '{print $10}' | sed 's/"//' | sort | uniq

Cyberfox/50.0.1
Firefox/30.0
Firefox/31.0
Firefox/32.0
Firefox/32.0.3
Firefox/33.1.1
Firefox/35.0
Firefox/35.0.1
Firefox/37.0.1
Firefox/37.0.2
Firefox/38.0.1
Firefox/38.0.5
Firefox/38.3.0
Firefox/38.8.0
Firefox/39.0
Firefox/39.0.3
Firefox/40.0.2
Firefox/40.0.3
Firefox/41.0.1
Firefox/41.0.2
Firefox/42.0
Firefox/43.0.1
Firefox/43.0.2
Firefox/44.0
Firefox/44.0.2
Firefox/45.0
Firefox/45.0.1
Firefox/45.0.2
Firefox/45.2.0
Firefox/45.3.0
Firefox/45.4.0
Firefox/45.5.1
Firefox/45.6.0
Firefox/45.7.0
Firefox/45.8.0
Firefox/45.9.0
Firefox/46.0
Firefox/46.0.1
Firefox/46.0a2
Firefox/47.0
Firefox/47.0.1
Firefox/47.0.2
Firefox/48.0
Firefox/48.0.1
Firefox/48.0.2
Firefox/49.0
Firefox/49.0.1
Firefox/49.0.2
Firefox/50.0
Firefox/50.0.1
Firefox/50.0.2
Firefox/50.1.0
Firefox/51.0
Firefox/51.0.1
Firefox/55.0a1
IceDragon/50.0.0.2
Mozilla/5.0
````

**Comment by rfk** [comment]
> Firefox/55.0a1

That's current nightly right?  I guess this should be covered by the existing "download in batches" work on desktop.

**Comment by mostlygeek** [comment]
What would be fallout from clients not getting all of their bookmarks? 
Working with @kitcambridge I can verify that go-sync has all the records.

**Comment by rfk** [comment]
ISTM that the client would just fail to sync down some of the bookmarks, but would think it had got all of them, so it wouldn't recover from this state until you e.g. make some more changes to bookmarks and trigger another sync.  Depending on what subset of the bookmark state the device receives, it might believe there to be bookmark corruption due to "missing" records.
