### ISSUE TITLE
Firefox sends unacceptable "Accept" headers

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-syncstorage#85]
@jrgm was accidentally testing it and ran into a 406 on `GET /collections/info`. Apparently firefox sends: `'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'`

Change the behavior of the AcceptHeaderOk ([link](https://github.com/mostlygeek/go-syncstorage/blob/559c384fb282923fc08d51e4751b88c1974c789d/web/misc.go#L224) so it defaults to `application/json` for unacceptable headers.

**Comment by jrgm** [comment]
I'll note that that Accept header says "I'll take anything else if you don't have my first 3 choices": 
(`...;*/*;q=0.8`)

**Comment by jrgm** [comment]
![image](https://cloud.githubusercontent.com/assets/758162/15873649/7c0290c8-2cb4-11e6-9ed2-5718a110657d.png)
