### ISSUE TITLE
Implement Batch API support

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-syncstorage#92]
The Batch API allows multiple POST requests to be atomically committed. BSOs, like those that container bookmark folder structure, can point to other BSOs. If these are changed and their references are not consistent bad things happen. Sometimes, bad, unrecoverable things. 

The discussion started in [Bug 1250189](https://bugzilla.mozilla.org/show_bug.cgi?id=1250189) and the python implementation is happening in PR [mozilla-services/server-syncstorage/#36](https://github.com/mozilla-services/server-syncstorage/pull/36).

The batch api works like this: 
1. `POST /storage/collection/{name}?batch=true` - starts a new batch upload. Returns a batch id number
   - returns a JSON: `{"batch":"{batch_id}"}`
2. `POST /storage/collection/{name}?batch={batch_id}` - appends more BSOs to the batch
3. `POST /storage/collection/{name}?batch={batch_id}&commit=true` - commits a batch as a single atomic transaction
   - `POST .../?batch=true&commit=true` should work like a regular POST. Weird. 
4. `GET /info/configuration`  [python implementation](https://github.com/mozilla-services/server-syncstorage/blob/25556c07aaa5eefe307bdad1ac5b785ce99b9c56/syncstorage/views/__init__.py#L188-L201). Returns a json object with keys:  
   - max_request_bytes
   - max_post_records
   - max_post_bytes
   - max_total_records
   - max_total_bytes
5. `X-Weave-*` batch headers from client
   - `X-Weave-Total-Records` - total records in batch
   - `X-Weave-Total-Bytes` - total amount of bytes in batch
   - `X-Weave-Bytes` - size of upload 

Some implementation notes: 
- Validate all BSOs in the POST, so don't have to wait until everything is uploaded before failing
- Keep pending batch BSOs in a `batch_jobs` table. Keep BSOs as text blobs
- When committing, just load the raw blobs, and commit them with `syncstorage.DB.putBSO` to reuse the same DB logic.
- Use the new batch Python functional tests to validate I got it right :)

**Comment by Micheletto** [comment]
Random thought: use new sqlite files for the batch uploads instead of batch tables inside the BSO sqlite files.

**Comment by mostlygeek** [comment]
> use new sqlite files for the batch uploads instead of batch tables inside the BSO sqlite files

The best reason for using another db file is to control excessive free db pages. Though, I think we need some real production traffic to see how it really is.

**Comment by Micheletto** [comment]
> The best reason for using another db file is to control excessive free db pages. Though, I think we need some real production traffic to see how it really is.

True.  An interesting point surrounding that observation is that in a running database those free pages get reclaimed by other users in aggregate.  It would be interesting to instrument stats around the batch API usage.
