### ISSUE TITLE
Reduce database open/close with caching

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/go-syncstorage#99]
Stats from one day of traffic from a production sync node: 

Distribution of requests by method/path:

```
SELECT method,p path,round(c / 1821216.0 * 100,2) pct 
    FROM (
        SELECT method, 
               case when instr(path,"?")>0 then substr(path,1,instr(path,"?")-1) else path end as p,
               count(*) c
        FROM d 
        GROUP BY method,p 
        ORDER BY c desc limit 25
    ) 
WHERE pct > 0.9;

method  path                      pct
------  ------------------------  ----------
GET     info/collections          33.75
POST    storage/tabs              15.09
POST    storage/history           13.13
GET     storage/meta/global       8.05
GET     storage/clients           7.41
GET     storage/tabs              4.8
POST    storage/clients           4.21
GET     storage/crypto/keys       3.98
POST    storage/passwords         2.35
POST    storage/forms             2.24
GET     storage/history           1.4

```

Min, Max and Average unique users per time period:

```
period    min         max         avg
-------- ----------  ----------  ----------
second   1           36          12.0
minute   15          535         370.0
hour     7058        13077       10525.0
```

This shows a lot of open/close churn. It means that go-syncstorage will be opening and closing a lot of files if it has to go to disk. 

The lowest hanging fruit would be to answer GET requests to:
1. `info/collections`
2. `storage/meta/global`
3. `storage/clients`

from RAM. These three endpoints make up close to 50% of GET requests.

@rfk @bbangert @Micheletto any thoughts?

**Comment by mostlygeek** [comment]
fyi: 

I created this [shell script](https://gist.github.com/mostlygeek/f81e44142e8634ffd18eda0b118c1399) to  the nginx sync server access logs into an sqlite3 database. 

That's where the above SQL data comes from.

**Comment by mostlygeek** [comment]
Another question is if we even need caching. 

```
sqlite> select min(c) min,max(c) max,round(avg(c)) avg 
  FROM (SELECT strftime("%H-%M-%S",date) t,count(*) c from d group by t);

min         max         avg
----------  ----------  ----------
1           73          21.0
```

A max of 73 requests per second for a fully loaded server wouldn't even cause the golang server to burp. On a c4.large with 1TB/3K IOPS, it could easily handle ~400req/second in the benchmarks. The the limit was really running out of IOPS from the EBS resource. 

@karlht any info from the stage server load testing?

**Comment by bbangert** [comment]
Is there any reason the node actually has to close handles that quickly? Why not leave a few tens of thousands open at a time?

A few kernel tweaks and it can handle the file descriptors no prob. There should be plenty of RAM free, and then perhaps more of those GET's can be cached as well.

**Comment by mostlygeek** [comment]
> Why not leave a few tens of thousands open at a time?

RAM. Without any tweaking each user handler uses about 1.37MB of RAM. Not entirely sure the right balance for the number of open files. Maybe use up as much RAM as possible?

**Comment by bbangert** [comment]
Sure, I just mean that leaving a few hundreds open at a time might avoid closing handles that are going to be re-opened shortly.

**Comment by mostlygeek** [comment]
## caching `tabs/storage`
- each client writes a single BSO with the current tabs. So one BSO per syncing client.
- these records are fairly small. and can be kept in RAM
- they need to behave like the regular API, as clients will try to get all tabs first before POSTing changes
- the POST will change the BSO for a client. So the data is updated every few minutes (not very often)
- data is quite transient. It's OK if it is lost. 

Ideas for keeping it in memory: 
- use the `uid` as the key
- data would be `map[string]syncstorage.BSO`. 
- data would be serialized and saved as json as a single key/value store. ie: the whole tabs collection for a user would be a single key+value
- for GET storage/tabs, it can filter out with a simple loop. Simply filter with the `newer` key.
- for POST, the whole collection is pulled, modified and saved to RAM again
- perhaps use memcache? or bigcache?

**Comment by mostlygeek** [comment]
In PR #129 info/collections and info/configuration is cached. This has helped with db open/close! :) Closing this issue.
